<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div id="modal-product-info" class="modal-product-content" data-bind="scope: 'productAdded'">
    <div class="product-image">
        <img data-bind="attr: {
            'src': productItem()?.product_image.src,
            'alt': productItem()?.product_image.alt,
            'height': productItem()?.product_image.height,
            'width': productItem()?.product_image.width
        }"/>
    </div>
    <div class="product-name">
        <span data-bind="text: productItem()?.product_name"></span>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "productAdded": {
                        "component": "Joao_ModalProductCart/js/product-added"
                    }
                }
            }
        }
    }
</script>
